version: "3.8"

services:
  mariadb:
    image: bitnami/mariadb:latest
    container_name: moodle_db
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - ./mariadb_data:/bitnami/mariadb
    networks:
      - moodle-net

  moodle:
    image: bitnamilegacy/moodle:latest
    container_name: moodle_app
    user: "1001"
    restart: always
    depends_on:
      - mariadb
    ports:
      - "${MOODLE_PORT}:8080"
      - "${MOODLE_SSL_PORT}:8443"
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=${DB_USER}
      - MOODLE_DATABASE_PASSWORD=${DB_PASSWORD}
      - MOODLE_DATABASE_NAME=${DB_NAME}
      - MOODLE_USERNAME=${MOODLE_ADMIN_USER}
      - MOODLE_PASSWORD=${MOODLE_ADMIN_PASSWORD}
      - MOODLE_EMAIL=${MOODLE_ADMIN_EMAIL}
      - MOODLE_SITE_NAME=${MOODLE_SITE_NAME}
      # Production settings
      - MOODLE_HOST=${MOODLE_HOST}
      - MOODLE_REVERSEPROXY=${MOODLE_REVERSEPROXY}
      - MOODLE_SSLPROXY=${MOODLE_SSLPROXY}
      - PHP_MEMORY_LIMIT=512M
      - BITNAMI_DEBUG=true
    volumes:
      - ./moodle_data:/bitnami/moodle
      - ./moodledata_data:/bitnami/moodledata
    networks:
      - moodle-net

networks:
  moodle-net:
    driver: bridge
